# Build
FROM golang:1.26.3-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o transcode-worker ./cmd/worker/main.go

# Runtime image with ffmpeg
FROM alpine:3.20
RUN apk --no-cache add ffmpeg ca-certificates
WORKDIR /app
COPY --from=builder /app/transcode-worker .
ENTRYPOINT ["./transcode-worker"]
