// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Video struct {
	ID               uuid.UUID          `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	OriginalFilename string             `json:"original_filename"`
	StoredFilename   string             `json:"stored_filename"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
