// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: video.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
  id, title, description, original_filename, stored_filename, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, title, description, original_filename, stored_filename, created_at, updated_at
`

type CreateVideoParams struct {
	ID               uuid.UUID          `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	OriginalFilename string             `json:"original_filename"`
	StoredFilename   string             `json:"stored_filename"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.OriginalFilename,
		arg.StoredFilename,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OriginalFilename,
		&i.StoredFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, title, description, original_filename, stored_filename, created_at, updated_at FROM videos
WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OriginalFilename,
		&i.StoredFilename,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
